# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]


# http://christopherpoole.github.io/using-mathjax-on-github-pages/
# markdown: kramdown
# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Tumbleweed
tagline: notes and ramblings
author :
  name : Willem Duminy
  email : willem.duminy@gmail.com
  github : Codespear

url : http://codespear.github.io
github_username:  codespear
JB:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  rss_path : /rss.xml
